name: jr_front
description: "Jeen Robotics Front"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  geolocator: ^14.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  permission_handler: ^11.3.0
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^18.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
