// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Jeen Robotics Camera library
class Camera {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Camera(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Camera.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<jr_android_camera_streamer_t>
      jr_android_camera_streamer_create() {
    return _jr_android_camera_streamer_create();
  }

  late final _jr_android_camera_streamer_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<jr_android_camera_streamer_t>
              Function()>>('jr_android_camera_streamer_create');
  late final _jr_android_camera_streamer_create =
      _jr_android_camera_streamer_createPtr
          .asFunction<ffi.Pointer<jr_android_camera_streamer_t> Function()>();

  void jr_android_camera_streamer_destroy(
    ffi.Pointer<jr_android_camera_streamer_t> streamer,
  ) {
    return _jr_android_camera_streamer_destroy(
      streamer,
    );
  }

  late final _jr_android_camera_streamer_destroyPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<jr_android_camera_streamer_t>)>>(
      'jr_android_camera_streamer_destroy');
  late final _jr_android_camera_streamer_destroy =
      _jr_android_camera_streamer_destroyPtr.asFunction<
          void Function(ffi.Pointer<jr_android_camera_streamer_t>)>();

  int jr_android_camera_streamer_initialize(
    ffi.Pointer<jr_android_camera_streamer_t> streamer,
    int width,
    int height,
    int format,
  ) {
    return _jr_android_camera_streamer_initialize(
      streamer,
      width,
      height,
      format,
    );
  }

  late final _jr_android_camera_streamer_initializePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<jr_android_camera_streamer_t>, ffi.Int32,
              ffi.Int32, ffi.Int32)>>('jr_android_camera_streamer_initialize');
  late final _jr_android_camera_streamer_initialize =
      _jr_android_camera_streamer_initializePtr.asFunction<
          int Function(
              ffi.Pointer<jr_android_camera_streamer_t>, int, int, int)>();

  int jr_android_camera_streamer_start_streaming(
    ffi.Pointer<jr_android_camera_streamer_t> streamer,
  ) {
    return _jr_android_camera_streamer_start_streaming(
      streamer,
    );
  }

  late final _jr_android_camera_streamer_start_streamingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Pointer<jr_android_camera_streamer_t>)>>(
      'jr_android_camera_streamer_start_streaming');
  late final _jr_android_camera_streamer_start_streaming =
      _jr_android_camera_streamer_start_streamingPtr.asFunction<
          int Function(ffi.Pointer<jr_android_camera_streamer_t>)>();

  void jr_android_camera_streamer_stop_streaming(
    ffi.Pointer<jr_android_camera_streamer_t> streamer,
  ) {
    return _jr_android_camera_streamer_stop_streaming(
      streamer,
    );
  }

  late final _jr_android_camera_streamer_stop_streamingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<jr_android_camera_streamer_t>)>>(
      'jr_android_camera_streamer_stop_streaming');
  late final _jr_android_camera_streamer_stop_streaming =
      _jr_android_camera_streamer_stop_streamingPtr.asFunction<
          void Function(ffi.Pointer<jr_android_camera_streamer_t>)>();

  void jr_android_camera_streamer_set_frame_callback(
    ffi.Pointer<jr_android_camera_streamer_t> streamer,
    jr_android_camera_frame_callback_t callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _jr_android_camera_streamer_set_frame_callback(
      streamer,
      callback,
      user_data,
    );
  }

  late final _jr_android_camera_streamer_set_frame_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<jr_android_camera_streamer_t>,
                  jr_android_camera_frame_callback_t, ffi.Pointer<ffi.Void>)>>(
      'jr_android_camera_streamer_set_frame_callback');
  late final _jr_android_camera_streamer_set_frame_callback =
      _jr_android_camera_streamer_set_frame_callbackPtr.asFunction<
          void Function(ffi.Pointer<jr_android_camera_streamer_t>,
              jr_android_camera_frame_callback_t, ffi.Pointer<ffi.Void>)>();
}

final class jr_android_camera_streamer extends ffi.Opaque {}

typedef jr_android_camera_streamer_t = jr_android_camera_streamer;
typedef jr_android_camera_frame_callback_tFunction = ffi.Void Function(
    ffi.Pointer<ffi.Uint8> data,
    ffi.Size size,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartjr_android_camera_frame_callback_tFunction = void Function(
    ffi.Pointer<ffi.Uint8> data, int size, ffi.Pointer<ffi.Void> user_data);
typedef jr_android_camera_frame_callback_t = ffi
    .Pointer<ffi.NativeFunction<jr_android_camera_frame_callback_tFunction>>;
